### ISSUE TITLE
BPM Detection?

### ISSUE THREAD

**Issue by ghost** [peterkhayes/pitchfinder#16]
I don't really know much about music so I apologize for any foolishness I speak in advance. I am running some sample trials using a piano app on my phone and I am getting back way more pitches than I am producing. I started tinkering with the BPM config and it did have an inverse effect on the number of pitches I am finding, leading to me this question: do you have or know of a module that will determine bpm for me? Or is there something I am overlooking?

**Comment by peterkhayes** [comment]
In the original use case I wrote pitchfinder for, the BPM was already known. I'm not super familiar with bpm detection but there seem to be some BPM detection libraries on NPM - try checking one of those out!
