### ISSUE TITLE
Algorithm suggestion

### ISSUE THREAD

**Issue by MysteryPancake** [peterkhayes/pitchfinder#18]
Hello! I've been looking around for a good JavaScript pitch detector, and I came across your repository. I have tried each of the algorithms, each with varying results, as would be expected.

[I would just like to suggest another algorithm](https://github.com/cwilso/PitchDetect/pull/23).

This algorithm appears to be capable of detecting notes while a chord is played, as well as accurately detecting low notes. I have found it to be very useful, so I just wanted to suggest it.

[You can download the website to test it here](https://github.com/dalatant/PitchDetect/archive/master.zip).

Thanks for reading!

**Comment by peterkhayes** [comment]
This sounds pretty cool! I'm not actively working on this repo now, but some day I could see adding this. I'd also accept a pull request, if you're interested!
