### ISSUE TITLE
Question - any complete example of use with a browser?

### ISSUE THREAD

**Issue by donpinkus** [peterkhayes/pitchfinder#20]

**Comment by donpinkus** [comment]
This will get you the pitch values. However, I'm not sure how to relate the pitch values to an actual note.

For example, given a pitch value of `154.73684210526315`, is that an A#?

```
navigator.getUserMedia(
      { audio: true },
      stream => {
        audioContext.createMediaStreamSource(stream).connect(analyser);

        const arrayUInt = new Uint8Array(analyser.frequencyBinCount);
        analyser.getByteTimeDomainData(arrayUInt);

        setInterval(() => {
          const array32 = new Float32Array(analyser.fftSize);
          analyser.getFloatTimeDomainData(array32);
          console.log(array32);

          const pitch = detectPitch(array32);
          
          console.log(pitch);
        }, 500);
      },
      err => console.log(err)
    );
```

**Comment by donpinkus** [comment]
Looks like this is the map from Hz (returned by pitchfinder) to note value:

http://pages.mtu.edu/~suits/notefreqs.html

**Comment by peterkhayes** [comment]
That looks right. You also might want to see this page to do these calculations programmatically: https://pages.mtu.edu/~suits/NoteFreqCalcs.html

**Comment by chrisspen** [comment]
@donpinkus What's the value of `analyzer`? You don't define it anywhere, and I assume that's not the pitch analyzer because you reference that separately as `detectPitch`.

**Comment by peterkhayes** [comment]
I think it's this https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode

There's a `frequencyBinCount` on it
