### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vmollov** [peterkhayes/pitchfinder#3]
First of all, thank you for this module - it pretty much rocks and is the awsomest thing I have seen in a while!
This is not an issue with your code, just a question.  I am pretty new to the domain of digital sound.  I want to use your code to create an app for ear training in ancient modes.  I wanted to ask your help in figuring out how to create a gate - I want to trigger pitch detection only on frequencies with amplitude greater than a certain configurable level.  Just using the YIN as it is can probably do the trick, but I am getting a C# calculated out of background noise (pretty high frequency: 17640).  I can always just discard pitches above say 15000, but if you can help me out with a better way I'd greatly appreciate it.

**Comment by peterkhayes** [comment]
Hi vmollov - using a filter is probably the best way to do this.  YIN seems to be susceptible to detecting very high frequencies.  I would like to add support for filtering the sound before analysis to future versions of this library.

Another alternative is to use a combination of multiple algorithms.  AMDF does not seem to have this problem as much, though it is not as accurate.  Check out `tools/frequencies.js` (in the new version) to see my first attempt at averaging the results of multiple pitch detectors.

**Comment by vmollov** [comment]
Thank you!
