### ISSUE TITLE
Add tests for ACF2PLUS

### ISSUE THREAD

**Issue by MysteryPancake** [peterkhayes/pitchfinder#38]
It would be good to see how this one compares to the others. I have found it to be the most accurate, but I would like to see if this is really the case.

**Comment by peterkhayes** [comment]
Some basic tests are already in place:
* We instantiate a detector here: https://github.com/peterkhayes/pitchfinder/blob/master/test/index.ts#L22
* We run tests for each detector here: https://github.com/peterkhayes/pitchfinder/blob/master/test/index.ts#L28

Tests for the frequencies tool would be interesting to add though, yeah
