### ISSUE TITLE
More info about the detector options?

### ISSUE THREAD

**Issue by nth-chile** [peterkhayes/pitchfinder#39]
For example, I'd like to try adjusting these values but I'm not sure what "threshold" or "sensitivity" or "ratio" mean exactly, or which number ranges to try

> YIN
>      threshold - used by the algorithm
>      probabilityThreshold - don't return a pitch if probability estimate is below this number.
> AMDF
>      minFrequency - Lowest frequency detectable
>      maxFrequency - Highest frequency detectable
>      sensitivity
>      ratio

**Comment by peterkhayes** [comment]
I'm not sure if I can give a general answer other than "try out some values and see what works for you"

- The YIN (non-probability) threshold is described [in the paper](http://audition.ens.fr/adc/pdf/2002_JASA_YIN.pdf)
- I'm not really sure about the other two, they might have been from the implementation I ported this code from
