### ISSUE TITLE
Detecting multiple pitches simultaneously?

### ISSUE THREAD

**Issue by chrisspen** [peterkhayes/pitchfinder#42]
I think this is more of a feature request,  but it there any way to use this library to detect multiple pitches at once?

I'm trying to write an app to detect the presence of a chord,  which would require being able to detect two or three pitches at the same time. Is this possible?

**Comment by peterkhayes** [comment]
That's a significantly harder problem than detecting one pitch and kind of beyond the scope of this library for now.

**Comment by chrisspen** [comment]
Turned out to be a lot easier than I thought. See my fork [here](https://github.com/chrisspen/chord_detector) of a chord detector project. Looks abandoned but I managed to patch some bugs and  get it working. I had to extend the underlying [chord detector](https://github.com/chrisspen/Chord-Detector-and-Chromagram) C++ project to return the raw pitch spectrum, but that seems to work pretty well for my application.

**Comment by peterkhayes** [comment]
Looks cool! Closing this issue here, though.
