### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by WeTruck** [peterkhayes/pitchfinder#43]
Hi,

Thanks for the package.

What is the license here?

Can I use this library in my app and upload to play store?

Thanks.

**Comment by peterkhayes** [comment]
According to `package.json`, at some point in the past, I picked the `GNU v3` license. You can read details about that [here](https://www.gnu.org/licenses/gpl-3.0.en.html).

**Comment by peterkhayes** [comment]
To briefly answer your question, yes, you can

**Comment by WeTruck** [comment]
@peterkhayes Thanks.
