### ISSUE TITLE
How to pass in config?

### ISSUE THREAD

**Issue by chrisspen** [peterkhayes/pitchfinder#44]
The README suggests most algorithms accept some optional configuration parameters, but there's no documentation on how to do this.

In the code, I see objects like `AMDFConfig`, but it's unclear how we use these to adjust parameters

How do you customize parameters?

**Comment by peterkhayes** [comment]
You can see the list of parameters in the README [here](https://github.com/peterkhayes/pitchfinder#configuration)

For example:

```ts
const myDetector = new Pitchfinder.AMDF({
    minFrequency: 1000,
    maxFrequency: 10000,
})
```

**Comment by chrisspen** [comment]
Thanks.
