### ISSUE TITLE
why can NOT detect any pitches from audioBuffer

### ISSUE THREAD

**Issue by alex2wong** [peterkhayes/pitchfinder#49]
I use the lib in es6 browser env

```
let pitches = [];
    const detectPitch = Pitchfinder.AMDF();
    const floatArray = this.audioBuffer.getChannelData(0);
    pitches = detectPitch(floatArray);    // takes long time
    console.log(`### detect pitches: ${pitches} from ${floatArray}`);
    return pitches;
```
console.log print as follow:

> ### detect pitches: null from 0,-0.000030517578125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000030518509447574615,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000030517578125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000030517578125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000030517578125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000030517578125,0,0,0,-0.000030517578125,0,0,0,0,0,0.000030518509447574615,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.000030518509447574615,0,0,0,0,-0.000030517578125,0,0,0,0,-0.000030517578125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.000030517578125,0,0,0,0,0.000030518509447574615,0,0,-0.000030517578125,0,0,0,0,0,0,0,0.000030518509447574615,0.000030518509447574615,0,0,0,0,-0.000030517578125,0,0,0,0,0,0.000030518509447574615,0,0,0,0,0,0,0,0,0,-0.000030517578125,...

Why can not detect any pitches from this audioBuffer(including some other piano audio or vocal singing) ?  I've test this audio on some deep learning model, it can detect some pitches. 

could you pls provide some **demo web page** with sample audio ? thanks a lot :)

**Comment by peterkhayes** [comment]
How long is the audio buffer? The function you're calling can only detect a single pitch. If it's a long file, you need to slice it up into small pieces. The [frequencies tool](https://github.com/peterkhayes/pitchfinder/blob/master/src/tools/frequencies.ts) can help with that if you have a tempo. Or you can slice it up manually

**Comment by alex2wong** [comment]
thx, I'd like to close this issue for now~
