### ISSUE TITLE
Pitchfinder.frequencies is not a function

### ISSUE THREAD

**Issue by chrisspen** [peterkhayes/pitchfinder#52]
I'm attempting to use the frequencies() function, as shown in the README, but the browser's reporting:

    Uncaught TypeError: Pitchfinder.frequencies is not a function

I'm importing Pitchfinder just as you described, with:

    const Pitchfinder = require('pitchfinder');

Is there anything else I need to do to fix this error?

**Comment by peterkhayes** [comment]
Ah, this is due to the difference between ES modules and commonjs `require`. You can make it work by doing:
```js
const Pitchfinder = require('pitchfinder').default;
```

**Comment by peterkhayes** [comment]
I'm putting up a PR that fixes the above issue.
