### ISSUE TITLE
license wanted!

### ISSUE THREAD

**Issue by ivosdc** [peterkhayes/pitchfinder#55]
Cool thing the pitchfinder! I'm currently working with MIT License in my project, can I use this product?

It would be helpful in these days to have a proper license-type for this great job!
E.g. GPL3 over all, regarding the dependency to aubio or better an individual licence-type for each algorithm pastet as comment in the file-header.

best

**Comment by peterkhayes** [comment]
I will add a license at some point. In the mean time, if you don't need anything formal, feel free to use this project in any MIT-licensed project

**Comment by ivosdc** [comment]
Ty. Fine for me.
