### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MistakingManx** [peterkhayes/pitchfinder#59]
I tried copying the code and using it, but it hangs at the pitch detector.
This leads me to believe that I don't properly understand what I'm supposed to do.

So, taking a vocals-only clip from a song (without editing) and including the audio areas with no noise, would this cause issues?

_Note: I tried giving it a 5 second clip with no silence and now it returns null, tested with multiple different files_

**Comment by peterkhayes** [comment]
In general I would recommend giving this short segments of audio, no more than a few hundred ms. The goal is to have the same pitch for the full segment of audio. A five second clip will probably have many pitches.

You can try using the "frequencies" utility as documented [here](https://github.com/peterkhayes/pitchfinder?tab=readme-ov-file#finding-a-series-of-pitches), if you know the tempo of the clip.
