### ISSUE TITLE
yin.js based on aubio, but does not mention it

### ISSUE THREAD

**Issue by piem** [peterkhayes/pitchfinder#8]
Hi @peterkhayes ,

It seems that yin.js is largely based on aubio's YIN implementation. It would be nice if you could add the copyright and license of the original implementation.

See: https://github.com/aubio/aubio/blob/master/src/pitch/pitchyin.c

cheers, piem

**Comment by peterkhayes** [comment]
I believe I ported yin from Tarsos's project - this was several years ago, but I remember only reading Java code, not C.  But he may have based his code on Aubio's code, so I'll add the info and change license to GNU v3
